In [1]:
import h5py

In [2]:
simulation = h5py.File('/disk1/lbignone/data/cielo/simulations/LG1/LG1.hdf5', 'r')

In [19]:
Group = simulation['SnapNumber_128/Groups']

In [20]:
Group.keys()

<KeysViewHDF5 ['Contamination', 'GroupCM', 'GroupLen', 'GroupLenType', 'GroupMassType', 'GroupNsubs', 'GroupNumber', 'GroupSFR', 'Group_M_Crit200', 'Group_M_Mean200', 'Group_M_TopHat200', 'Group_R_Crit200', 'Group_R_Mean200', 'Group_R_TopHat200', 'PartType0', 'PartType1', 'PartType4', 'PartType5', 'SnapNumber']>

In [21]:
Group['Contamination'].keys()

<KeysViewHDF5 ['PartType5']>

In [22]:
Group['GroupCM'].attrs['cgs_conversion_factor']

3.085678e+21

In [23]:
Group['GroupCM'][()]

array([[52797.62 , 50642.95 , 45243.082],
       [49187.85 , 47752.58 , 43493.113],
       [48191.67 , 47116.14 , 44133.55 ],
       ...,
       [52985.324, 49328.48 , 46111.887],
       [53369.48 , 49184.168, 46335.49 ],
       [53678.22 , 48915.32 , 46731.97 ]], dtype=float32)

In [25]:
Group['PartType0/Offsets'][()]

array([[372825., 431577.],
       [444372., 501993.],
       [525023., 534704.],
       ...,
       [966768., 966769.],
       [967066., 967067.],
       [967562., 967563.]])

In [26]:
Part = simulation['SnapNumber_128/PartType0']

In [28]:
Part['Abundances'].attrs['description']

'Mass in individual elements: He, C, Mg, O, Fe, Si, H, N, Ne, S, Ca, Zi (in this order)'

In [29]:
Part['Abundances'][()]

array([[3.40601309e-06, 3.16166364e-08, 7.88885846e-09, ...,
        1.38015555e-08, 1.83959581e-09, 1.52504787e-10],
       [5.17143826e-06, 8.53428048e-08, 2.09202842e-08, ...,
        3.71073448e-08, 4.94864727e-09, 4.08520662e-10],
       [6.48430751e-06, 5.08869142e-08, 1.08120792e-08, ...,
        2.13509264e-08, 2.86493229e-09, 2.29623431e-10],
       ...,
       [5.80772621e-06, 3.17144568e-08, 7.06553305e-09, ...,
        1.35762139e-08, 1.81743720e-09, 1.40816789e-10],
       [4.74920989e-06, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.45053218e-06, 3.10285273e-08, 6.35315756e-09, ...,
        1.26573996e-08, 1.70913006e-09, 1.31912495e-10]], dtype=float32)

In [32]:
Part['Abundances'][372825: 431577]

array([[4.9806317e-06, 6.6649943e-09, 1.3167956e-09, ..., 2.5853482e-09,
        3.4952746e-10, 2.3014710e-11],
       [2.4232581e-06, 1.5189356e-09, 3.2480532e-10, ..., 7.5449696e-10,
        1.0207920e-10, 6.5692495e-12],
       [2.7886483e-06, 8.8911092e-09, 1.3091541e-09, ..., 2.5429951e-09,
        3.7353237e-10, 4.8797400e-11],
       ...,
       [3.4895779e-06, 3.2873839e-08, 6.9310850e-09, ..., 1.3703188e-08,
        1.8248238e-09, 1.5127986e-10],
       [2.9667456e-06, 1.7069851e-08, 3.4633310e-09, ..., 7.6085902e-09,
        1.0553545e-09, 6.5057890e-11],
       [3.0525869e-06, 1.9914577e-08, 4.0222217e-09, ..., 8.6992333e-09,
        1.1917137e-09, 7.4357735e-11]], dtype=float32)

In [33]:
Part.keys()

<KeysViewHDF5 ['Abundances', 'BindingEnergy', 'Circularity', 'Coordinates', 'Density', 'ElectronAbundance', 'Esn', 'EsnCold', 'GroupNumber', 'InternalEnergy', 'Masses', 'NeutralHydrogenAbundance', 'ParticleIDs', 'Potential', 'SmoothingLength', 'SpecificAngularMomentum', 'StarFormationRate', 'SubFindNumber', 'SubGroupNumber', 'Velocities']>

In [34]:
Pgas = simulation['SnapNumber_128/PartType0/Masses'][()]

In [36]:
Pgas.min()*1e10

98941.87314785086

In [43]:
np.log10(simulation['SnapNumber_128/Header/MassTable'][()]*1e10)

/home/srodriguez/miniconda3/envs/cielo_old/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 6.03515832,       -inf,       -inf,       -inf,
             -inf])

In [42]:
import numpy as np

In [46]:
simulation['SnapNumber_30/Header/Redshift'][()]

10.914255466808548

In [47]:
simulation['SnapNumber_128/Header/Redshift'][()]

2.220446049250313e-16